name: "Build with MPLAB X, XC32, Harmony and Ceedling"
description: "This action builds an MPLABX/XC32/Harmony project in a Linux container and tests with Ceedling if enabled."
branding:
  icon: speaker
  color: gray-dark

inputs:
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: "default"
  harmonyAppsFolder:
    description: Harmony apps folder if you want to build inside apps for references
    required: false
    default: ""
  ceedling:
    description: If you have Ceedling at the root level and you want to run tests
    required: false
    default: "false"

runs:
  using: "docker"
  image: docker://ghcr.io/soundboks/ghactions-mplabx-xc32:latest
  args:
    - ${{ inputs.project }}
    - ${{ inputs.configuration }}
    - ${{ inputs.harmonyAppsFolder }}
    - ${{ inputs.ceedling }}
